Models/Module.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Study_Tracker.Models
{
    public class Module
    {

        [Key]
        [MaxLength(50)]
        public string moduleCode { get; set; } = null!; // Module code.
        [MaxLength(50)]
        public string moduleName { get; set; } = null!; // Module name.
        public int credits { get; set; } // Module credits.
        public double classHoursPerWeek { get; set; } // The number of class hours there are for a week.
        [NotMapped]
        private double? hoursStudiedThisWeek; // How many hours studied this week.
        public int semesterNumOfWeeks { get; set; } // How many weeks in a semester
        public DateTime semesterStartDate { get; set; } // When does the semester starts

        public virtual User user { get; set; } = null!;
        public virtual ICollection<StudyDate>? studyDates { get; set; } = null!;

        [NotMapped]
        public double HoursStudiedThisWeek
        {
            get
            {
                if(studyDates != null && studyDates.Count > 0)
                {
                    double hours = 0;
                    foreach(StudyDate entry in studyDates)
                    {
                        if (DatesAreInTheSameWeek(entry.date, DateTime.Now)) // If the date was this week.
                        {
                            hours += entry.hoursStudied; // Add to the sum of all hours studied for this week.
                        }
                    }
                    return hours;
                }
                return 0;
            }

            set
            {
                HoursStudiedThisWeek = value;
            }
        }

        /* Checks if 2 dates are in the same week.
         * The week starts on a Monday.
         * Taken from https://stackoverflow.com/questions/25795254/check-if-a-datetime-is-in-same-week-as-other-datetime
         * Authored by Sparrow on Aug 5, 2016 at 14:55
         */
        private bool DatesAreInTheSameWeek(DateTime date1, DateTime date2)
        {
            var cal = System.Globalization.DateTimeFormatInfo.CurrentInfo.Calendar;
            var d1 = date1.Date.AddDays(-1 * (int)(cal.GetDayOfWeek(date1) - 1));
            var d2 = date2.Date.AddDays(-1 * (int)(cal.GetDayOfWeek(date2) - 1));

            return d1 == d2;
        }

        [NotMapped]
        public double RecommendedStudyHours
        {
            get
            {
                return ((credits * 10) / semesterNumOfWeeks) - classHoursPerWeek; // Provided formula.
            }

            set
            {
                RecommendedStudyHours = value;
            }
        }
    }
}

Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Security.Claims;
using System.Threading.Tasks;
using EntityFramework.Exceptions.Common;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Study_Tracker.Data;
using Study_Tracker.Models;
using Module = Study_Tracker.Models.Module;

namespace Study_Tracker.Controllers
{
    public class ModulesController : Controller
    {
        //private readonly User _user;
        private readonly Study_TrackerContext _context;

        public ModulesController(Study_TrackerContext context)
        {
            _context = context;
        }

        // GET: Modules
        public async Task<IActionResult> Index()
        {
            List<Module> modules = await _context.Module.Where(a => a.user.username == User.FindFirstValue(ClaimTypes.NameIdentifier)).ToListAsync();

			return View(modules);
        }

        // GET: Modules/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Module == null)
            {
                return NotFound();
            }

            var @module = await _context.Module.Include("studyDates")
                .FirstOrDefaultAsync(m => m.moduleCode == id);

            if (@module == null)
            {
                return NotFound();
            }


            if(module.studyDates != null)
            {
                List<StudyDate> dates = module.studyDates.OrderBy(o => o.date).ToList();

                List<DataPoint> points = new List<DataPoint>();

                foreach (var d in dates)
                {
                    DataPoint dp = new DataPoint(d.date, d.hoursStudied);
                    points.Add(dp);
                }

                ViewBag.DataPoints = JsonConvert.SerializeObject(points);
            }

            return View(@module);
        }

        // GET: Modules/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Modules/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("moduleCode,moduleName,credits,classHoursPerWeek,semesterNumOfWeeks,semesterStartDate")] Module @module)
        {
            ModelState.Remove("user");
            if (ModelState.IsValid)
            {     
                User _user = await _context.User.FirstAsync(a => a.username == User.FindFirstValue(ClaimTypes.NameIdentifier));
                @module.user = _user;
                _context.Add(@module);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (UniqueConstraintException ex)
                {
                    ViewData["ValidateMessage"] = ex.Message;
                    return View();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@module);
        }

        // GET: Modules/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Module == null)
            {
                return NotFound();
            }

            var @module = await _context.Module.FindAsync(id);
            if (@module == null)
            {
                return NotFound();
            }
            return View(@module);
        }

        // POST: Modules/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("moduleCode,moduleName,credits,classHoursPerWeek,semesterNumOfWeeks,semesterStartDate")] Module @module)
        {
            if (id != @module.moduleCode)
            {
                return NotFound();
            }

            ModelState.Remove("user");
            if (ModelState.IsValid)
            {
                try
                {
                    User _user = await _context.User.FirstAsync(a => a.username == User.FindFirstValue(ClaimTypes.NameIdentifier));
                    module.user = _user;
                    _context.Update(@module);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModuleExists(@module.moduleCode))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@module);
        }

        // GET: Modules/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Module == null)
            {
                return NotFound();
            }

            var @module = await _context.Module
                .FirstOrDefaultAsync(m => m.moduleCode == id);
            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }

        // POST: Modules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Module == null)
            {
                return Problem("Entity set 'Study_TrackerContext.Module'  is null.");
            }
            var @module = await _context.Module.FindAsync(id);
            if (@module != null)
            {
                _context.Module.Remove(@module);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ModuleExists(string id)
        {
          return _context.Module.Any(e => e.moduleCode == id);
        }

        public async Task<IActionResult> AddStudyTime(string id)
        {
            if (id == null || _context.Module == null)
            {
                return NotFound();
            }

            var @module = await _context.Module.Include("studyDates")
                .FirstOrDefaultAsync(m => m.moduleCode == id);
            if (@module == null)
            {
                return NotFound();
            }

            ViewData["ModuleHoursThisWeek"] = module.HoursStudiedThisWeek;
            ViewData["ModuleRecommendedHours"] = module.RecommendedStudyHours;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddStudyTime(string id, [Bind("hoursStudied")] StudyDate studyDate)
        {
            if (id == null || _context.Module == null)
            {
                return NotFound();
            }

            var @module = await _context.Module.FindAsync(id);
            if (@module == null)
            {
                return NotFound();
            }

            ModelState.Remove("module");
            ModelState.Remove("date");

            studyDate.module = module;
            studyDate.date = DateTime.Now;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(studyDate);
                    await _context.SaveChangesAsync();
                }
                catch (UniqueConstraintException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@studyDate);
        }
    }
}

Views/Modules/AddStudyTime.cshtml
@model Study_Tracker.Models.StudyDate
@{
    ViewData["Title"] = "Create";
}

<h1>Add Time Studied</h1>
<hr />
<h3>
    You have studied @ViewData["ModuleHoursThisWeek"] hours so far this week out of the @ViewData["ModuleRecommendedHours"] recommended hours.
</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Modules" asp-action="AddStudyTime" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="hoursStudied" class="control-label">How many hours did you study?</label>
                <input asp-for="hoursStudied" class="form-control" />
                <span asp-validation-for="hoursStudied" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Modules/Create.cshtml
@model Study_Tracker.Models.Module

@{
    ViewData["Title"] = "Create";
}

<h1>Create A Module</h1>

<h4>Module</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="moduleCode" class="control-label">Module Code</label>
                <input asp-for="moduleCode" class="form-control" />
                <span asp-validation-for="moduleCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="moduleName" class="control-label">Module Name</label>
                <input asp-for="moduleName" class="form-control" />
                <span asp-validation-for="moduleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="credits" class="control-label">Module Credits</label>
                <input asp-for="credits" class="form-control" />
                <span asp-validation-for="credits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="classHoursPerWeek" class="control-label">Class Hours Per Week</label>
                <input asp-for="classHoursPerWeek" class="form-control" />
                <span asp-validation-for="classHoursPerWeek" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="semesterNumOfWeeks" class="control-label">Number Of Weeks in the Semester</label>
                <input asp-for="semesterNumOfWeeks" class="form-control" />
                <span asp-validation-for="semesterNumOfWeeks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="semesterStartDate" class="control-label">When does the Semester Start</label>
                <input asp-for="semesterStartDate" class="form-control" />
                <span asp-validation-for="semesterStartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@if (ViewData["ValidateMessage"] != null)
{
    <hr />
    <label>@ViewData["ValidateMessage"]</label>
    <hr />
}

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Modules/Delete.cshtml
@model Study_Tracker.Models.Module

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete @Model.moduleCode</h1>

<h3>Are you sure you want to delete @Model.moduleCode? This action cannot be undone.</h3>
<div>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="moduleCode" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Modules/Details.cshtml
@model Study_Tracker.Models.Module

@{
    ViewData["Title"] = "Details";
}
<head>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</head>

<div>
    <h1>Details for @Html.DisplayFor(model => model.moduleCode)</h1>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Module Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.moduleName)
        </dd>
        <dt class = "col-sm-2">
            Module Credits
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.credits)
        </dd>
        <dt class = "col-sm-2">
            Class Hours Per Week
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.classHoursPerWeek)
        </dd>
        <dt class = "col-sm-2">
            Hours Studied This Week
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoursStudiedThisWeek)
        </dd>
        <dt class="col-sm-2">
           Recommended Hours Of Studying.
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RecommendedStudyHours)
        </dd>
        <dt class = "col-sm-2">
            Weeks in Semester
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.semesterNumOfWeeks)
        </dd>
        <dt class = "col-sm-2">
            Semester start date
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.semesterStartDate)
        </dd>
    </dl>
</div>
<br />
<br />
<div id="chartContainer" style="height: 350px; width: 80%;"></div>

<script type="text/javascript">

    window.onload = function () {
        var chart = new CanvasJS.Chart("chartContainer", {
            animationEnabled: true,
            theme: "light2",
            title: {
                text: "Number of hours spent studying for @Model.moduleCode per week."
            },
            axisY: {
                title: "Hours Studied"
            },
            data: [
                {
                    type: "column",
                    xValueType: "dateTime",
                    showInLegend: true, 
		            legendMarkerColor: "grey",
		            legendText: "Hours",
                    dataPoints: @Html.Raw(ViewBag.DataPoints)
                    }
            ]
        });
        chart.render();
    };
</script>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.moduleCode">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Modules/Edit.cshtml
@model Study_Tracker.Models.Module

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit @Model.moduleCode</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="moduleCode" />
            <div class="form-group">
                <label asp-for="moduleName" class="control-label">Module Name</label>
                <input asp-for="moduleName" class="form-control" />
                <span asp-validation-for="moduleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="credits" class="control-label">Module Credits</label>
                <input asp-for="credits" class="form-control" />
                <span asp-validation-for="credits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="classHoursPerWeek" class="control-label">Class Hours Per Week</label>
                <input asp-for="classHoursPerWeek" class="form-control" />
                <span asp-validation-for="classHoursPerWeek" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="semesterNumOfWeeks" class="control-label">Number Of Weeks In the Semester</label>
                <input asp-for="semesterNumOfWeeks" class="form-control" />
                <span asp-validation-for="semesterNumOfWeeks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="semesterStartDate" class="control-label">Semester Start Date</label>
                <input asp-for="semesterStartDate" class="form-control" />
                <span asp-validation-for="semesterStartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Modules/Index.cshtml
@model IEnumerable<Study_Tracker.Models.Module>

@{
    ViewData["Title"] = "Index";
}
<h1>List of Your Modules</h1>

<p>
    <a asp-action="Create">Create A New Module</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Module Name
            </th>
            <th>
                Module Code
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.moduleName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.moduleCode)
                </td>
                <td>
                </td>
                <td>
                    <a asp-action="AddStudyTime" asp-route-id="@item.moduleCode">Add Time Studied</a> |
                    <a asp-action="Edit" asp-route-id="@item.moduleCode">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.moduleCode">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.moduleCode">Delete</a>
                </td>
            </tr>
        }
    </tbody>

</table>